- name: Upgrade all packages to their latest version
  become: True
  package:
    name: '*'
    state: latest

- name: Clean package manager data (dnf)
  become: True
  shell: |
    dnf clean all --enablerepo=\*
  args:
    warn: False
  when: ansible_pkg_mgr == 'dnf'

- name: Clean package manager data (apt)
  become: True
  shell: |
    apt-get clean -y
    apt-get autoclean -y
  args:
    warn: False
  when: ansible_pkg_mgr == 'apt'

- name: Install vagrant certificate
  copy:
    src: authorized_keys
    dest: /home/vagrant/.ssh/authorized_keys
    owner: vagrant
    group: vagrant
    mode: 0600

- name: Zero out disk space
  become: True
  shell: |
    # Remove bash history
    unset HISTFILE
    [ -f /root/.bash_history ] && rm /root/.bash_history
    [ -f /home/vagrant/.bash_history ] && rm /home/vagrant/.bash_history
    
    # Truncate log files
    find /var/log -type f | while read f; do echo -ne '' > $f; done;

    # Zero out unused disk space
    # There is only one partition and no swap
    count=`df --sync -kP / | tail -n1  | awk -F ' ' '{print $4}'`; 
    let count--
    dd if=/dev/zero of=/tmp/whitespace bs=1024 count=$count;
    rm /tmp/whitespace;
